version: "3"
services:
  redis:
    image: redis
    container_name: microservice_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    restart: always

  redis_insight:
    image: redislabs/redisinsight
    container_name: microsercice_redis_insight
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db
    restart: always

networks:
  default:
    external:
      name: microservice_network

volumes:
  redis_data: {}
  redis_insight_data: {}